

- name: Ensure older packages are removed
  yum:
    name: "{{percona_toolkit_remove_packages}}"
    state: absent

#- name: install perl-dbd-mysql outside of percona
#  yum:
#    name: perl-DBD-MySQL
#    state: latest
#    disablerepo: percona*

- name: Install packages from percona repo
  yum:
    name: "{{percona_toolkit_packages}}"
    state: latest
    enablerepo: percona-release*




- name: Install other mysql tools from yum
  yum:
    name: "{{mysql_tool_packages}}"
    state: latest
    enablerepo: percona-release*



