

- name: Ensure older packages are removed
  yum:
    name: "{{item}}"
    state: absent
  with_items: "{{percona_toolkit_remove_packages}}"

- name: Install packages from percona repo
  yum:
    name: "{{item}}"
    state: latest
  with_items: "{{percona_toolkit_packages}}"




- name: Install other mysql tools from yum
  yum:
    name: "{{item}}"
    state: latest
  with_items: "{{mysql_tool_packages}}"



