
- name: Add percona yum repository
  yum:
    name: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
    state: present


# - name: Add mydumper yum repository
#   shell: curl -s https://packagecloud.io/install/repositories/twindb/main/script.rpm.sh | sudo bash

